### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null (JS)

### ISSUE THREAD

**Issue by apohllo** [chrismccord/labrador#11]
I'm trying to use Labrador, but I get this error in JS code. I run Chromium on Linux. The full stack trace is as follows:

```
Uncaught TypeError: Cannot read property 'path' of null application-72df6c149fa3bd426580a5507ec8ce7b.js:13
App.n.initialize                application-72df6c149fa3bd426580a5507ec8ce7b.js:13
s.Callbacks.d                 application-72df6c149fa3bd426580a5507ec8ce7b.js:9
s.Callbacks.v.fireWith   application-72df6c149fa3bd426580a5507ec8ce7b.js:9
i.extend.ready                 application-72df6c149fa3bd426580a5507ec8ce7b.js:9
n.addEventListener.k    application-72df6c149fa3bd426580a5507ec8ce7b.js:9 
```

**Comment by chrismccord** [comment]
Are you possibly hitting the app via the root url, i.e. `http://localhost:7488`? The only way I can replicate this is to not include any application path, which the error is then expected. Labrador currently has no landing page. It expects to always have an application associated, although a landing page of some sort is something I plan on adding. Are things working properly for you if you give it an app path in the URL? ie. `http://localhost:7488/~/Path/to/myapp` ?

**Comment by apohllo** [comment]
Unfortunately the problem is present even with the path supplied.

**Comment by chrismccord** [comment]
This sounds like a path issue where labrador is unable to find the application directory. There have been a few commits on master to better handle subdomains and application path discovery. Are you by any chance accessing labrador over a subdomain? If so, please update to the latest build and try again, this could be related to a couple fixes pushed out this weekend. Please also try using a root path if the relative still doesn't work after update. i.e.
`http://localhost:7488/~/Path/to/myapp` to `http://localhost:7488/Users/apohllo/Path/to/myapp`

**Comment by apohllo** [comment]
Thanks!
