### ISSUE TITLE
Settings dialog behind overlay

### ISSUE THREAD

**Issue by schwarz** [chrismccord/labrador#12]
When clicking on the cog to display the settings dialog, they overlay prevents you from interacting with it. It closes again after you click anywhere on the screen.

I don't know if this is because settings haven't been implemented yet but thought it would be best to point this out.

**Comment by chrismccord** [comment]
This sounds like a z-index issue. I am able to access the dialog input and controls without issue on Safari/Chrome/Firefox. What browser are you using?

**Comment by schwarz** [comment]
Chrome 22 on OSX Mountain Lion

**Comment by chrismccord** [comment]
I can replicate this on my own Chrome 22 OSX. This must have slipped in from a recent chrome update. I should have things patched up tomorrow.

**Comment by chrismccord** [comment]
This has been fixed on master. To update your local copy:

```
$ cd ~/.labrador
$ git pull origin master
$ mkdir -p tmp/
$ touch tmp/restart.txt
```

 Thanks for catching this.
