### ISSUE TITLE
Unknown alias: test

### ISSUE THREAD

**Issue by lodestone** [chrismccord/labrador#20]
https://gist.github.com/lodestone/4749922

Getting this:

```
Psych::BadAlias (Unknown alias: test):
  lib/labrador/adapter.rb:82:in `database_yml_config'
  lib/labrador/adapter.rb:43:in `configuration'
  lib/labrador/adapter.rb:102:in `valid?'
  lib/labrador/app.rb:102:in `block in find_adapters_from_path'
  lib/labrador/app.rb:96:in `each'
  lib/labrador/app.rb:96:in `find_adapters_from_path'
  lib/labrador/app.rb:84:in `initialize'
  lib/labrador/app.rb:26:in `new'
  lib/labrador/app.rb:26:in `block in find_all_from_path'
  lib/labrador/app.rb:23:in `each'
  lib/labrador/app.rb:23:in `find_all_from_path'
  app/controllers/application_controller.rb:69:in `find_applications'
```

Adding a - raise "#{@path}/#{file}" to app.rb inside of find_adapters_from_path - I get:

```
RuntimeError (/Users/matt/.pow/labrador/config/database.yml)
```

First off, am I just doing something wrong? I tried to follow the instructions as written but I had a few errors so I had to run them one by one with localized corrections. (ruby version etc.)

**Comment by chrismccord** [comment]
Can you provide the contents (strip out credentials if necessary) of the database.yml file that might be throwing this? The first raise looks like labrador's own file, but I'm willing to bet it's another database.yml file from another pow app on a subsequent call that is causing this issue. Particularly, the yml file might be using an alias, although this shouldn't halt the entire process, so we might need to patch this case. Can you describe the issues you had following the instructions as written? Did the copy paste install fail at particular points? Also what ruby version are you running?

```
$ cd ~/.labrador && ruby -v
```

As a quick check to pinpoint the application throwing the error you could modify adapter.rb#database_yml_config to wrap the yml load and report which path is failing to load (after removing your other manual raise from app.rb):

``` ruby

begin   
  config = YAML.load(ERB.new(File.read(path)).result)
rescue Exception => message
  raise path.to_s
end
```

**Comment by chrismccord** [comment]
Any luck with this?

**Comment by lodestone** [comment]
Okay, I just pulled the latest code and I was still having this issue. 

The fix was to remove the symlink pointing to the app with the following database.yml:

```
production:
  adapter: sqlite3
  database: db/production.db

development:
  adapter: sqlite3
  database: db/development.db

profile:
  adapter: sqlite3
  database: db/development.db

test: &TEST
  adapter: sqlite3
  database: db/test.db

cucumber:
  <<: *test
```

But now I'm curious, why would that have caused labrador to choke?

**Comment by chrismccord** [comment]
Thanks for following up on this. I'm still settling back in to my work flow, but I'll take a look soon. Thanks!
