### ISSUE TITLE
Error: You have already activated json 1.8.0 but Gemfile requires 1.7.7

### ISSUE THREAD

**Issue by joefiorini** [chrismccord/labrador#25]
This happened after running your install script and then going to labrador for a given app. Might be related to 37signals/pow#378? Thoughts?

**Comment by chrismccord** [comment]
Hmm. It sounds like some have had success manually  patching nack. Can you try throwing `gem 'json', '1.7.7'` in your `~/.labrador/Gemfile` as a quick workaround?

**Comment by joefiorini** [comment]
I had to actually manually update the Gemfile.lock since labrador does
deployment bundles by default. I got working by making Labrador use json
1.8.0.
