### ISSUE TITLE
Documentation and startup

### ISSUE THREAD

**Issue by janlimpens** [chrismccord/labrador#9]
Sorry, if this is not the right place for suggestions and questions just tell me and I will direct myself elsewhere…

I just setup a labrador instance on my web server, there is no pow, but nginx listening to a certain port, connected via passenger to the rails app.

When requesting / , I get this in my logs:

Processing by PagesController#home as HTML
Completed 500 Internal Server Error in 3ms

Errno::ENOENT (No such file or directory - /home/jl/.pow):
  lib/labrador/app.rb:18:in `open'
  lib/labrador/app.rb:18:in`entries'
  lib/labrador/app.rb:18:in `find_all_from_path'
  app/controllers/application_controller.rb:48:in`find_applications’

so, this seems, either I am missing something important or (as it seems) not using pow is not an option - but this is what your home page suggests (one can get an installation without both pow and osx, and being on a linux server that was what I chose).

```
def apps_path
  if request.subdomain.present?
    path = "~/.pow" 
  else
    path = File.expand_path("#{path_param}/../")
  end
  path
end
```

Then, how is one supposed to setup the database to use? Just by adding database.yml or mongoid.yml? Delete the other? Anything else? One sentence or two might make these things quite a bit clearer…

Cheers and thanks for the effort!!

—jan

**Comment by janlimpens** [comment]
I just found out that you can get by the .pow error by just creating that directory…
Still none of my mongo databases are found

**Comment by chrismccord** [comment]
Labrador will happily run on a Linux box. Are you by any chance running labrador on an app with a subdomain? That's the only way I see this happening. At the moment, labrador assumes you are using pow if your request has a subdomain (ie myapp.labrador.dev). Alternatively, running the app without pow such as localhost:3000/~/Path/to/myapp, will not set the app path to ~/.pow. If my assumption is right and your setup is using some kind of subdomain, Labrador is mistakenly trying to set your application path as ~/.pow. I think we need some more sophisticated check like:

```
def apps_path
  if request.subdomain.present? && File.exist?(File.expand_path("~/.pow"))
    path = "~/.pow" 
  else
    path = File.expand_path("#{path_param}/../")
  end
  path
end
```

Let me know and I'll get this patched on master. Thanks

**Comment by janlimpens** [comment]
Your assumptions are correct and this seems to work quite well :)
If I only would find out what I need to do to see a db somewhere…! ;)

**Comment by chrismccord** [comment]
If you aren't seeing any tables, you might be missing the application path that needs to be supplied in the URL. For pow apps, this is handled automatically, but non pow apps need to tell labrador where their app lives. ie:
via process owners' relative home path `http://subdomain.somehost/~/Path/to/myapp` or root path `http://subdomain.somehost/Users/janlimpens/Path/to/myapp`. If you're passing the app path and still not seeing anything, we'll have to dig a little deeper.

**Comment by chrismccord** [comment]
This has been fixed on master. Please update and let me know if this resolves your issues. You should also delete the .pow directory you created.

**Comment by janlimpens** [comment]
Sorry for not replying for so long! How am I supposed to pass the app path? .powrc? In my case, there is no obvious mapping, I would have to pass it in somehow, so that if I go to app1.labrador.mysite.com, it would resolve to /home/someuser/apps/rails_app_for_superstuff and something completely different for app2.

**Comment by chrismccord** [comment]
You can just pass the relative or full path through the url and labrador will parse it for the app path. i.e.:

`http://labrador.mysite.com/~/Sites/app1` or `http://labrador.mysite.com/Users/janlimpens/Sites/app1`

**Comment by chrismccord** [comment]
@janlimpens Did you have any luck passing the path through the url from my previous comment?

**Comment by janlimpens** [comment]
Chris McCord@06/102012:

> @janlimpens Did you have any luck passing the path through the url from my previous comment?
> 
> —
> Reply to this email directly or view it on GitHub.

Sorry, I was not able to try it out lately. Too much actual work :)
I will try to see to it during the next week!

## Abraços,

Jan

Jan Limpens
jan@limpens.com
http://limpens.com
Cel: +55 (11) 97909 6066

**Comment by janlimpens** [comment]
I just tried it, but ended up with a blank labrador environment (no data). The problem might lie in the fact, that mongoid.yaml takes its values from the web server process’s shell environment.
